"""isbn normal — keunikan & pencarian ISBN pada bentuk ternormalisasi (WP 5.3.5).

ASUMSI(OQ-13): `978-602-…`, `978602…`, dan `x`/`X` dianggap ISBN yang sama. Kolom `isbn` tetap seperti
diketik admin; kolom generated `isbn_normal` memegang UNIQUE dan indeks trigram (pencarian WP 5.3.2).
Upgrade sengaja gagal bila data lama sudah berisi ISBN yang sama setelah normalisasi.

Revision ID: 8ead55e364f2
Revises: ea28f897f6be
Create Date: 2026-10-02 16:14:27.778744+07:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ead55e364f2"
down_revision: str | Sequence[str] | None = "ea28f897f6be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "judul_buku",
        sa.Column(
            "isbn_normal",
            sa.Text(),
            sa.Computed("upper(regexp_replace(isbn, '[-[:space:]]', '', 'g'))", persisted=True),
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("ix_judul_buku_isbn_trgm"),
        table_name="judul_buku",
        postgresql_ops={"isbn": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_constraint(op.f("uq_judul_buku_isbn"), "judul_buku", type_="unique")
    op.create_index(
        "ix_judul_buku_isbn_normal_trgm",
        "judul_buku",
        ["isbn_normal"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"isbn_normal": "gin_trgm_ops"},
    )
    op.create_unique_constraint(op.f("uq_judul_buku_isbn_normal"), "judul_buku", ["isbn_normal"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_judul_buku_isbn_normal"), "judul_buku", type_="unique")
    op.drop_index(
        "ix_judul_buku_isbn_normal_trgm",
        table_name="judul_buku",
        postgresql_using="gin",
        postgresql_ops={"isbn_normal": "gin_trgm_ops"},
    )
    op.create_unique_constraint(
        op.f("uq_judul_buku_isbn"), "judul_buku", ["isbn"], postgresql_nulls_not_distinct=False
    )
    op.create_index(
        op.f("ix_judul_buku_isbn_trgm"),
        "judul_buku",
        ["isbn"],
        unique=False,
        postgresql_ops={"isbn": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("judul_buku", "isbn_normal")
    # ### end Alembic commands ###
