"""sesi — tabel sesi login (WP 5.3.1).

ASUMSI(OQ-04): token opaque, hanya hash SHA-256 yang disimpan; kedaluwarsa geser 8 jam (NFR-SEC-04)
dihitung di Python dari `terakhir_aktif` (tanpa server_default now(), K-07).
ASUMSI(OQ-17): satu akun boleh punya beberapa sesi aktif.

Revision ID: ea28f897f6be
Revises: 5ed9d0b605f4
Create Date: 2026-10-02 15:41:30.719790+07:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea28f897f6be"
down_revision: str | Sequence[str] | None = "5ed9d0b605f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sesi",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("admin_id", sa.BigInteger(), nullable=True),
        sa.Column("anggota_id", sa.BigInteger(), nullable=True),
        sa.Column("dibuat_pada", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terakhir_aktif", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(role = 'ADMIN' AND admin_id IS NOT NULL AND anggota_id IS NULL) OR (role = 'ANGGOTA' AND anggota_id IS NOT NULL AND admin_id IS NULL)",
            name=op.f("ck_sesi_pemilik_sesuai_role"),
        ),
        sa.CheckConstraint("role IN ('ADMIN', 'ANGGOTA')", name=op.f("ck_sesi_role")),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admin.id"], name=op.f("fk_sesi_admin_id_admin"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["anggota_id"],
            ["anggota.id"],
            name=op.f("fk_sesi_anggota_id_anggota"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sesi")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sesi_token_hash")),
    )
    op.create_index(op.f("ix_sesi_admin_id"), "sesi", ["admin_id"], unique=False)
    op.create_index(op.f("ix_sesi_anggota_id"), "sesi", ["anggota_id"], unique=False)
    op.create_index(op.f("ix_sesi_terakhir_aktif"), "sesi", ["terakhir_aktif"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sesi_terakhir_aktif"), table_name="sesi")
    op.drop_index(op.f("ix_sesi_anggota_id"), table_name="sesi")
    op.drop_index(op.f("ix_sesi_admin_id"), table_name="sesi")
    op.drop_table("sesi")
    # ### end Alembic commands ###
