/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Memeriksa aplikasi hidup dan basis data dapat dihubungi.
     */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/daftar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Daftar
     * @description FR-AKN-01..04: pendaftaran publik; akun langsung aktif, tanpa login otomatis (OQ-30).
     */
    post: operations["daftar_api_v1_auth_daftar_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description FR-AKN-05: login admin/anggota; sesi baru di cookie (OQ-04).
     */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description FR-AKN-06: akhiri sesi di server dan kosongkan cookie.
     */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/saya": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Saya
     * @description Identitas pemilik sesi, agar frontend dapat mengarahkan sesuai role (FR-AKN-05).
     */
    get: operations["saya_api_v1_auth_saya_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/katalog/judul": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cari Judul */
    get: operations["cari_judul_api_v1_katalog_judul_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/katalog/judul/{judul_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail Judul */
    get: operations["detail_judul_api_v1_katalog_judul__judul_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/katalog/judul/{judul_id}/cover": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cover Judul */
    get: operations["cover_judul_api_v1_katalog_judul__judul_id__cover_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/kategori": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Daftar Kategori */
    get: operations["daftar_kategori_api_v1_admin_kategori_get"];
    put?: never;
    /** Tambah Kategori */
    post: operations["tambah_kategori_api_v1_admin_kategori_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/kategori/{kategori_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Ubah Kategori */
    put: operations["ubah_kategori_api_v1_admin_kategori__kategori_id__put"];
    post?: never;
    /** Hapus Kategori */
    delete: operations["hapus_kategori_api_v1_admin_kategori__kategori_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/rak": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Daftar Rak */
    get: operations["daftar_rak_api_v1_admin_rak_get"];
    put?: never;
    /** Tambah Rak */
    post: operations["tambah_rak_api_v1_admin_rak_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/rak/{rak_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Ubah Rak */
    put: operations["ubah_rak_api_v1_admin_rak__rak_id__put"];
    post?: never;
    /** Hapus Rak */
    delete: operations["hapus_rak_api_v1_admin_rak__rak_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/judul": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Daftar Judul */
    get: operations["daftar_judul_api_v1_admin_judul_get"];
    put?: never;
    /** Tambah Judul */
    post: operations["tambah_judul_api_v1_admin_judul_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/judul/{judul_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail Judul */
    get: operations["detail_judul_api_v1_admin_judul__judul_id__get"];
    /** Ubah Judul */
    put: operations["ubah_judul_api_v1_admin_judul__judul_id__put"];
    post?: never;
    /** Hapus Judul */
    delete: operations["hapus_judul_api_v1_admin_judul__judul_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/judul/{judul_id}/cover": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Ganti Cover
     * @description NFR-SEC-06: JPG/PNG ≤ 2 MB, diperiksa dari isi. Nama berkas dari klien diabaikan.
     */
    put: operations["ganti_cover_api_v1_admin_judul__judul_id__cover_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/judul/{judul_id}/eksemplar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stok Judul
     * @description FR-BKU-09: rekap stok per judul + daftar eksemplarnya.
     */
    get: operations["stok_judul_api_v1_admin_judul__judul_id__eksemplar_get"];
    put?: never;
    /**
     * Tambah Eksemplar
     * @description FR-BKU-04: tambah satu atau beberapa eksemplar sekaligus (atomik).
     */
    post: operations["tambah_eksemplar_api_v1_admin_judul__judul_id__eksemplar_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/eksemplar/label": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Data Label
     * @description FR-BKU-06: data label (kode, judul singkat, isi QR). Cetak A4 di frontend (WP 5.4.7).
     */
    get: operations["data_label_api_v1_admin_eksemplar_label_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/eksemplar/{eksemplar_id}/rak": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Ubah Rak
     * @description FR-BKU-05: ubah rak; status tidak berubah (ASUMSI(OQ-21)).
     */
    put: operations["ubah_rak_api_v1_admin_eksemplar__eksemplar_id__rak_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/eksemplar/{eksemplar_id}/rusak": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Tandai Rusak
     * @description FR-BKU-07 / K-02: Tersedia → Rusak tanpa tagihan. FR-BKU-08: Dipinjam ditolak.
     */
    post: operations["tandai_rusak_api_v1_admin_eksemplar__eksemplar_id__rusak_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/peminjaman/anggota/{kode}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Identifikasi Anggota
     * @description FR-PJM-01/02: kode dari QR anggota atau diketik; tampilkan kelayakan beserta alasannya.
     */
    get: operations["identifikasi_anggota_api_v1_admin_peminjaman_anggota__kode__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/peminjaman/validasi-item": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validasi Item
     * @description FR-PJM-05..08: periksa satu pindaian terhadap keranjang. Tidak mengubah data.
     */
    post: operations["validasi_item_api_v1_admin_peminjaman_validasi_item_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/peminjaman": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Konfirmasi
     * @description FR-PJM-10..12: periksa ulang, simpan transaksi dengan admin pemroses dari sesi.
     */
    post: operations["konfirmasi_api_v1_admin_peminjaman_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/pengembalian/{kode_eksemplar}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Pratinjau
     * @description FR-KMB-01..04: item aktif, peminjam, hari terlambat, dan denda sebelum konfirmasi.
     */
    get: operations["pratinjau_api_v1_admin_pengembalian__kode_eksemplar__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/pengembalian": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Konfirmasi
     * @description FR-KMB-05..08: tanggal kembali = hari ini WIB (OQ-25), tagihan denda bila > 0.
     */
    post: operations["konfirmasi_api_v1_admin_pengembalian_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/hilang-rusak/anggota/{kode}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Daftar Item Anggota
     * @description FR-HLR-01: item Dipinjam milik anggota (kode dari QR atau diketik). Tidak mengubah data.
     */
    get: operations["daftar_item_anggota_api_v1_admin_hilang_rusak_anggota__kode__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/hilang-rusak": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Catat
     * @description FR-HLR-01..04: catat Hilang/Rusak + tagihan Penggantian; admin pencatat dari sesi.
     */
    post: operations["catat_api_v1_admin_hilang_rusak_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/tagihan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Daftar
     * @description FR-TGH-01: daftar tagihan dengan filter status, jenis, dan anggota.
     */
    get: operations["daftar_api_v1_admin_tagihan_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/tagihan/{tagihan_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations["detail_api_v1_admin_tagihan__tagihan_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/tagihan/{tagihan_id}/penyelesaian": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Selesaikan
     * @description FR-TGH-02..05: Tunai/Transfer (nominal sama persis) atau Buku Pengganti.
     */
    post: operations["selesaikan_api_v1_admin_tagihan__tagihan_id__penyelesaian_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/anggota": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cari
     * @description FR-AKN-10: daftar & pencarian anggota.
     */
    get: operations["cari_api_v1_admin_anggota_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/anggota/{kode}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations["detail_api_v1_admin_anggota__kode__get"];
    /**
     * Ubah
     * @description FR-AKN-11, K-03: ubah data selain NIK/foto; `password_baru` mencabut semua sesi (OQ-32).
     */
    put: operations["ubah_api_v1_admin_anggota__kode__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Dashboard
     * @description FR-LAP-01: ringkasan judul, eksemplar per status, anggota, pinjaman, tagihan Belum Lunas.
     */
    get: operations["dashboard_api_v1_admin_dashboard_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/laporan/transaksi": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Laporan Transaksi
     * @description FR-LAP-02: laporan peminjaman & pengembalian per item.
     */
    get: operations["laporan_transaksi_api_v1_admin_laporan_transaksi_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/laporan/transaksi/ekspor": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ekspor Transaksi
     * @description FR-LAP-04: semua baris laporan transaksi sesuai filter aktif, sebagai PDF atau xlsx.
     */
    get: operations["ekspor_transaksi_api_v1_admin_laporan_transaksi_ekspor_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/laporan/tagihan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Laporan Tagihan
     * @description FR-LAP-03: laporan denda & penggantian beserta total nominal.
     */
    get: operations["laporan_tagihan_api_v1_admin_laporan_tagihan_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/laporan/tagihan/ekspor": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ekspor Tagihan
     * @description FR-LAP-04: semua baris laporan tagihan + total sesuai filter aktif, sebagai PDF atau xlsx.
     */
    get: operations["ekspor_tagihan_api_v1_admin_laporan_tagihan_ekspor_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anggota/profil": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Profil */
    get: operations["profil_api_v1_anggota_profil_get"];
    /**
     * Ubah Profil
     * @description FR-AKN-07/08: nama, alamat, email (cek unik lintas admin–anggota), telepon.
     */
    put: operations["ubah_profil_api_v1_anggota_profil_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anggota/profil/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Ganti Password
     * @description FR-AKN-09: wajib password lama; sesi lain akun ini dicabut (OQ-32).
     */
    put: operations["ganti_password_api_v1_anggota_profil_password_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anggota/qr": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Qr
     * @description FR-AGT-01: data QR identifikasi; gambar QR dibuat di klien (isi = kode anggota).
     */
    get: operations["qr_api_v1_anggota_qr_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anggota/kelayakan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Kelayakan
     * @description FR-AGT-05: status kelayakan meminjam beserta alasannya bila terblokir.
     */
    get: operations["kelayakan_api_v1_anggota_kelayakan_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anggota/pinjaman": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Pinjaman
     * @description FR-AGT-02: pinjaman aktif (maks. 3) dengan jatuh tempo, sisa hari, dan penanda terlambat.
     */
    get: operations["pinjaman_api_v1_anggota_pinjaman_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anggota/riwayat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Riwayat
     * @description FR-AGT-03: riwayat peminjaman & pengembalian, termasuk item Hilang/Rusak.
     */
    get: operations["riwayat_api_v1_anggota_riwayat_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anggota/tagihan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Tagihan
     * @description FR-AGT-04: tagihan dengan jenis, nominal, status, dan cara penyelesaian.
     */
    get: operations["tagihan_api_v1_anggota_tagihan_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AlasanKeluar */
    AlasanKeluar: {
      /** Kode */
      kode: string;
      /** Pesan */
      pesan: string;
      /** Rujukan */
      rujukan: string;
    };
    /**
     * BarisTagihanKeluar
     * @description FR-LAP-03, ASUMSI(OQ-39).
     */
    BarisTagihanKeluar: {
      /** Id */
      id: number;
      /**
       * Tanggal Dibentuk
       * Format: date
       */
      tanggal_dibentuk: string;
      /** Anggota Kode */
      anggota_kode: string;
      /** Anggota Nama */
      anggota_nama: string;
      /** Judul */
      judul: string;
      /** Kode Eksemplar */
      kode_eksemplar: string;
      jenis: components["schemas"]["JenisTagihan"];
      /** Nominal */
      nominal: number;
      status: components["schemas"]["StatusTagihan"];
      cara_penyelesaian: components["schemas"]["CaraPenyelesaian"] | null;
      /** Tanggal Penyelesaian */
      tanggal_penyelesaian: string | null;
      /** Admin Pengonfirmasi */
      admin_pengonfirmasi: string | null;
    };
    /**
     * BarisTransaksiKeluar
     * @description FR-LAP-02, ASUMSI(OQ-07): satu baris per item.
     */
    BarisTransaksiKeluar: {
      /** Anggota Kode */
      anggota_kode: string;
      /** Anggota Nama */
      anggota_nama: string;
      /** Judul */
      judul: string;
      /** Kode Eksemplar */
      kode_eksemplar: string;
      /**
       * Tanggal Pinjam
       * Format: date
       */
      tanggal_pinjam: string;
      /**
       * Jatuh Tempo
       * Format: date
       */
      jatuh_tempo: string;
      /** Tanggal Kembali */
      tanggal_kembali: string | null;
      status: components["schemas"]["StatusItem"];
      /** Terlambat */
      terlambat: boolean;
    };
    /** Body_daftar_api_v1_auth_daftar_post */
    Body_daftar_api_v1_auth_daftar_post: {
      /**
       * Nama
       * @default
       */
      nama: string;
      /**
       * Alamat
       * @default
       */
      alamat: string;
      /**
       * Email
       * @default
       */
      email: string;
      /**
       * Telepon
       * @default
       */
      telepon: string;
      /**
       * Nik
       * @default
       */
      nik: string;
      /**
       * Password
       * @default
       */
      password: string;
      /** Foto */
      foto?: string | null;
    };
    /** Body_ganti_cover_api_v1_admin_judul__judul_id__cover_put */
    Body_ganti_cover_api_v1_admin_judul__judul_id__cover_put: {
      /** Berkas */
      berkas: string;
    };
    /**
     * CaraPenyelesaian
     * @enum {string}
     */
    CaraPenyelesaian: "TUNAI" | "TRANSFER" | "BUKU_PENGGANTI";
    /** CatatMasuk */
    CatatMasuk: {
      /** Item Id */
      item_id: number;
      /**
       * Jenis
       * @enum {string}
       */
      jenis: "HILANG" | "RUSAK";
      /**
       * Tanggal Kejadian
       * Format: date
       */
      tanggal_kejadian: string;
      /** Keterangan */
      keterangan: string;
    };
    /** DaftarItemKeluar */
    DaftarItemKeluar: {
      anggota: components["schemas"]["app__schemas__hilang_rusak__AnggotaRingkas"];
      /** Item */
      item: components["schemas"]["ItemAktifKeluar"][];
    };
    /**
     * DashboardKeluar
     * @description FR-LAP-01. ASUMSI(OQ-40): `item_dipinjam` termasuk yang terlambat;
     *     `item_terlambat` bagiannya.
     */
    DashboardKeluar: {
      /** Jumlah Judul */
      jumlah_judul: number;
      /** Eksemplar Per Status */
      eksemplar_per_status: {
        [key: string]: number;
      };
      /** Jumlah Anggota */
      jumlah_anggota: number;
      /** Item Dipinjam */
      item_dipinjam: number;
      /** Item Terlambat */
      item_terlambat: number;
      /** Tagihan Belum Lunas Jumlah */
      tagihan_belum_lunas_jumlah: number;
      /** Tagihan Belum Lunas Total */
      tagihan_belum_lunas_total: number;
    };
    /** EksemplarKeluar */
    EksemplarKeluar: {
      /** Id */
      id: number;
      /** Kode */
      kode: string;
      /** Status */
      status: string;
      rak: components["schemas"]["RakKeluar"];
    };
    /** EksemplarRingkas */
    EksemplarRingkas: {
      /** Kode */
      kode: string;
      /** Judul */
      judul: string;
    };
    /**
     * GantiPasswordMasuk
     * @description FR-AKN-09. Tidak di-trim.
     */
    GantiPasswordMasuk: {
      /** Password Lama */
      password_lama: string;
      /** Password Baru */
      password_baru: string;
    };
    /** HalamanAnggota */
    HalamanAnggota: {
      /** Data */
      data: components["schemas"]["ProfilKeluar"][];
      /** Total */
      total: number;
      /** Halaman */
      halaman: number;
      /** Per Halaman */
      per_halaman: number;
    };
    /** HalamanJudul */
    HalamanJudul: {
      /** Data */
      data: components["schemas"]["JudulKeluar"][];
      /** Total */
      total: number;
      /** Halaman */
      halaman: number;
      /** Per Halaman */
      per_halaman: number;
    };
    /** HalamanKatalog */
    HalamanKatalog: {
      /** Data */
      data: components["schemas"]["JudulKatalogKeluar"][];
      /** Total */
      total: number;
      /** Halaman */
      halaman: number;
      /** Per Halaman */
      per_halaman: number;
    };
    /** HalamanRiwayat */
    HalamanRiwayat: {
      /** Data */
      data: components["schemas"]["ItemRiwayatKeluar"][];
      /** Total */
      total: number;
      /** Halaman */
      halaman: number;
      /** Per Halaman */
      per_halaman: number;
    };
    /** HalamanTagihan */
    HalamanTagihan: {
      /** Data */
      data: components["schemas"]["TagihanKeluar"][];
      /** Total */
      total: number;
      /** Halaman */
      halaman: number;
      /** Per Halaman */
      per_halaman: number;
    };
    /** HalamanTagihanAnggota */
    HalamanTagihanAnggota: {
      /** Data */
      data: components["schemas"]["TagihanAnggotaKeluar"][];
      /** Total */
      total: number;
      /** Halaman */
      halaman: number;
      /** Per Halaman */
      per_halaman: number;
    };
    /**
     * HasilDaftarKeluar
     * @description FR-AKN-04. Sengaja tanpa NIK, foto, dan hash password. `isi_qr` = kode anggota (teks
     *     polos); gambar QR dibuat frontend (IR-SW-02).
     */
    HasilDaftarKeluar: {
      /** Kode */
      kode: string;
      /** Nama */
      nama: string;
      /** Email */
      email: string;
      /** Isi Qr */
      isi_qr: string;
    };
    /**
     * IdentitasAnggotaKeluar
     * @description FR-PJM-02. Sengaja tanpa NIK, alamat, telepon, email, dan foto.
     */
    IdentitasAnggotaKeluar: {
      /** Id */
      id: number;
      /** Kode */
      kode: string;
      /** Nama */
      nama: string;
      /** Pinjaman Aktif */
      pinjaman_aktif: number;
      /** Layak */
      layak: boolean;
      /** Alasan */
      alasan: components["schemas"]["AlasanKeluar"][];
    };
    /** ItemAktifKeluar */
    ItemAktifKeluar: {
      /** Item Id */
      item_id: number;
      /** Kode Eksemplar */
      kode_eksemplar: string;
      /** Judul */
      judul: string;
      /**
       * Tanggal Pinjam
       * Format: date
       */
      tanggal_pinjam: string;
      /**
       * Jatuh Tempo
       * Format: date
       */
      jatuh_tempo: string;
      /** Hari Terlambat */
      hari_terlambat: number;
    };
    /** ItemDipinjamKeluar */
    ItemDipinjamKeluar: {
      /** Kode Eksemplar */
      kode_eksemplar: string;
      /** Judul */
      judul: string;
      /**
       * Tanggal Pinjam
       * Format: date
       */
      tanggal_pinjam: string;
      /**
       * Jatuh Tempo
       * Format: date
       */
      jatuh_tempo: string;
      status: components["schemas"]["StatusItem"];
    };
    /**
     * ItemRiwayatKeluar
     * @description FR-AGT-03. ASUMSI(OQ-35): tanpa `keterangan` dan admin pencatat.
     */
    ItemRiwayatKeluar: {
      /** Kode Eksemplar */
      kode_eksemplar: string;
      /** Judul */
      judul: string;
      /**
       * Tanggal Pinjam
       * Format: date
       */
      tanggal_pinjam: string;
      /**
       * Jatuh Tempo
       * Format: date
       */
      jatuh_tempo: string;
      /** Tanggal Kembali */
      tanggal_kembali: string | null;
      status: components["schemas"]["StatusItem"];
      /** Terlambat */
      terlambat: boolean;
      /** Tanggal Kejadian */
      tanggal_kejadian: string | null;
    };
    /** ItemValidKeluar */
    ItemValidKeluar: {
      /** Eksemplar Id */
      eksemplar_id: number;
      /** Kode */
      kode: string;
      /** Judul */
      judul: string;
    };
    /**
     * JenisTagihan
     * @enum {string}
     */
    JenisTagihan: "DENDA" | "PENGGANTIAN";
    /**
     * JudulKatalogKeluar
     * @description FR-KTL-01/03. Sengaja tanpa data per eksemplar (kode, status) dan tanpa data peminjam.
     */
    JudulKatalogKeluar: {
      /** Id */
      id: number;
      /** Isbn */
      isbn: string;
      /** Judul */
      judul: string;
      /** Penulis */
      penulis: string;
      /** Penerbit */
      penerbit: string;
      /** Tahun */
      tahun: number;
      kategori: components["schemas"]["KategoriKeluar"];
      /** Harga */
      harga: number;
      /** Cover Url */
      cover_url: string | null;
      /** Rak */
      rak: components["schemas"]["RakKatalogKeluar"][];
      /** Tersedia */
      tersedia: number;
      /** Total */
      total: number;
    };
    /** JudulKeluar */
    JudulKeluar: {
      /** Id */
      id: number;
      /** Isbn */
      isbn: string;
      /** Judul */
      judul: string;
      /** Penulis */
      penulis: string;
      /** Penerbit */
      penerbit: string;
      /** Tahun */
      tahun: number;
      kategori: components["schemas"]["KategoriKeluar"];
      /** Harga */
      harga: number;
      /** Cover Path */
      cover_path: string | null;
      /** Cover Url */
      readonly cover_url: string | null;
    };
    /** JudulMasuk */
    JudulMasuk: {
      /** Isbn */
      isbn: string;
      /** Judul */
      judul: string;
      /** Penulis */
      penulis: string;
      /** Penerbit */
      penerbit: string;
      /** Tahun */
      tahun: number;
      /** Kategori Id */
      kategori_id: number;
      /** Harga */
      harga: number;
    };
    /** KategoriKeluar */
    KategoriKeluar: {
      /** Id */
      id: number;
      /** Nama */
      nama: string;
    };
    /** KategoriMasuk */
    KategoriMasuk: {
      /** Nama */
      nama: string;
    };
    /**
     * KelayakanKeluar
     * @description FR-AGT-05. Pesan alasan sama persis dengan yang dilihat admin (§B, satu sumber kebenaran).
     */
    KelayakanKeluar: {
      /** Layak */
      layak: boolean;
      /** Alasan */
      alasan: components["schemas"]["AlasanKeluar"][];
    };
    /** LabelEksemplar */
    LabelEksemplar: {
      /** Kode */
      kode: string;
      /** Judul Singkat */
      judul_singkat: string;
      /** Isi Qr */
      isi_qr: string;
    };
    /**
     * LaporanTagihanKeluar
     * @description `total` = jumlah baris; `total_nominal` dari seluruh baris yang lolos filter
     *     (bukan halaman).
     */
    LaporanTagihanKeluar: {
      /** Data */
      data: components["schemas"]["BarisTagihanKeluar"][];
      /** Total */
      total: number;
      /** Total Nominal */
      total_nominal: number;
      /** Halaman */
      halaman: number;
      /** Per Halaman */
      per_halaman: number;
    };
    /** LaporanTransaksiKeluar */
    LaporanTransaksiKeluar: {
      /** Data */
      data: components["schemas"]["BarisTransaksiKeluar"][];
      /** Total */
      total: number;
      /** Halaman */
      halaman: number;
      /** Per Halaman */
      per_halaman: number;
    };
    /**
     * PeminjamRingkas
     * @description Sengaja tanpa NIK dan kontak.
     */
    PeminjamRingkas: {
      /** Kode */
      kode: string;
      /** Nama */
      nama: string;
    };
    /**
     * PencatatanKeluar
     * @description FR-HLR-03/04. Sengaja tanpa field denda (BR-15).
     */
    PencatatanKeluar: {
      /** Item Id */
      item_id: number;
      /** Kode Eksemplar */
      kode_eksemplar: string;
      /** Judul */
      judul: string;
      anggota: components["schemas"]["app__schemas__hilang_rusak__AnggotaRingkas"];
      status: components["schemas"]["StatusItem"];
      /**
       * Tanggal Kejadian
       * Format: date
       */
      tanggal_kejadian: string;
      /** Keterangan */
      keterangan: string;
      tagihan: components["schemas"]["TagihanRingkas"];
      /** Transaksi Selesai */
      transaksi_selesai: boolean;
    };
    /** PengembalianKeluar */
    PengembalianKeluar: {
      eksemplar: components["schemas"]["EksemplarRingkas"];
      peminjam: components["schemas"]["PeminjamRingkas"];
      /**
       * Tanggal Kembali
       * Format: date
       */
      tanggal_kembali: string;
      /** Hari Terlambat */
      hari_terlambat: number;
      tagihan: components["schemas"]["TagihanRingkas"] | null;
      /** Transaksi Selesai */
      transaksi_selesai: boolean;
    };
    /** PenyelesaianMasuk */
    PenyelesaianMasuk: {
      /**
       * Cara
       * @enum {string}
       */
      cara: "TUNAI" | "TRANSFER" | "BUKU_PENGGANTI";
      /** Nominal */
      nominal?: number | null;
      /**
       * Tanggal
       * Format: date
       */
      tanggal: string;
    };
    /** PermintaanLogin */
    PermintaanLogin: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * PinjamanAktifKeluar
     * @description FR-AGT-02. ASUMSI(OQ-34): `sisa_hari` ≥ 0; `hari_terlambat` terpisah.
     */
    PinjamanAktifKeluar: {
      /** Kode Eksemplar */
      kode_eksemplar: string;
      /** Judul */
      judul: string;
      /**
       * Tanggal Pinjam
       * Format: date
       */
      tanggal_pinjam: string;
      /**
       * Jatuh Tempo
       * Format: date
       */
      jatuh_tempo: string;
      /** Sisa Hari */
      sisa_hari: number;
      /** Terlambat */
      terlambat: boolean;
      /** Hari Terlambat */
      hari_terlambat: number;
    };
    /**
     * PratinjauKeluar
     * @description FR-KMB-02/04: informasi sebelum konfirmasi; nominal final di respons konfirmasi (OQ-25).
     */
    PratinjauKeluar: {
      eksemplar: components["schemas"]["EksemplarRingkas"];
      peminjam: components["schemas"]["PeminjamRingkas"];
      /**
       * Tanggal Pinjam
       * Format: date
       */
      tanggal_pinjam: string;
      /**
       * Jatuh Tempo
       * Format: date
       */
      jatuh_tempo: string;
      /** Hari Terlambat */
      hari_terlambat: number;
      /** Denda */
      denda: number;
    };
    /**
     * ProfilKeluar
     * @description FR-AKN-07/10. Sengaja tanpa `password_hash` dan `foto_path` (foto tidak disajikan).
     */
    ProfilKeluar: {
      /** Kode */
      kode: string;
      /** Nama */
      nama: string;
      /** Alamat */
      alamat: string;
      /** Email */
      email: string;
      /** Telepon */
      telepon: string;
      /** Nik */
      nik: string;
      /**
       * Tanggal Daftar
       * Format: date
       */
      tanggal_daftar: string;
    };
    /**
     * QrKeluar
     * @description FR-AGT-01. Sengaja hanya tiga isian ini (tanpa NIK, foto, kontak).
     */
    QrKeluar: {
      /** Kode */
      kode: string;
      /** Nama */
      nama: string;
      /** Isi Qr */
      isi_qr: string;
    };
    /** RakKatalogKeluar */
    RakKatalogKeluar: {
      /** Kode */
      kode: string;
      /** Lokasi */
      lokasi: string | null;
    };
    /** RakKeluar */
    RakKeluar: {
      /** Id */
      id: number;
      /** Kode */
      kode: string;
      /** Lokasi */
      lokasi: string | null;
    };
    /** RakMasuk */
    RakMasuk: {
      /** Kode */
      kode: string;
      /** Lokasi */
      lokasi?: string | null;
    };
    /** RekapStokKeluar */
    RekapStokKeluar: {
      /** Total */
      total: number;
      /** Tersedia */
      tersedia: number;
      /** Dipinjam */
      dipinjam: number;
      /** Hilang */
      hilang: number;
      /** Rusak */
      rusak: number;
    };
    /**
     * ResponsLogin
     * @description Frontend mengarahkan ke dashboard sesuai `role` (FR-AKN-05).
     */
    ResponsLogin: {
      role: components["schemas"]["Role"];
      /** Nama */
      nama: string;
    };
    /** ResponsSaya */
    ResponsSaya: {
      role: components["schemas"]["Role"];
      /** Nama */
      nama: string;
      /** Email */
      email: string;
    };
    /** Ringkas */
    Ringkas: {
      /** Kode */
      kode: string;
      /** Nama */
      nama: string;
    };
    /**
     * Role
     * @description Dua role terautentikasi (BR-02). Pengunjung umum bukan role.
     * @enum {string}
     */
    Role: "ADMIN" | "ANGGOTA";
    /**
     * StatusEksemplar
     * @enum {string}
     */
    StatusEksemplar: "TERSEDIA" | "DIPINJAM" | "HILANG" | "RUSAK";
    /** StatusHealth */
    StatusHealth: {
      /** Status */
      status: string;
      /** Database */
      database: string;
    };
    /**
     * StatusItem
     * @enum {string}
     */
    StatusItem: "DIPINJAM" | "DIKEMBALIKAN" | "HILANG" | "RUSAK";
    /**
     * StatusTagihan
     * @enum {string}
     */
    StatusTagihan: "BELUM_LUNAS" | "LUNAS";
    /** StokJudul */
    StokJudul: {
      /** Judul Id */
      judul_id: number;
      rekap: components["schemas"]["RekapStokKeluar"];
      /** Data */
      data: components["schemas"]["EksemplarKeluar"][];
    };
    /**
     * TagihanAnggotaKeluar
     * @description FR-AGT-04. ASUMSI(OQ-36): tanpa nama admin pengonfirmasi dan `nominal_dibayar`.
     */
    TagihanAnggotaKeluar: {
      /** Id */
      id: number;
      jenis: components["schemas"]["JenisTagihan"];
      /** Nominal */
      nominal: number;
      status: components["schemas"]["StatusTagihan"];
      cara_penyelesaian: components["schemas"]["CaraPenyelesaian"] | null;
      /**
       * Tanggal Dibentuk
       * Format: date
       */
      tanggal_dibentuk: string;
      /** Tanggal Penyelesaian */
      tanggal_penyelesaian: string | null;
      /** Kode Eksemplar */
      kode_eksemplar: string;
      /** Judul */
      judul: string;
    };
    /**
     * TagihanKeluar
     * @description FR-TGH-01/05. Kode status/jenis/cara dikirim apa adanya; label dipetakan klien (IR-UI-03).
     *     Anggota tanpa NIK/kontak; admin pengonfirmasi berupa nama.
     */
    TagihanKeluar: {
      /** Id */
      id: number;
      jenis: components["schemas"]["JenisTagihan"];
      /** Nominal */
      nominal: number;
      status: components["schemas"]["StatusTagihan"];
      /**
       * Tanggal Dibentuk
       * Format: date
       */
      tanggal_dibentuk: string;
      anggota: components["schemas"]["Ringkas"];
      eksemplar: components["schemas"]["EksemplarRingkas"];
      cara_penyelesaian: components["schemas"]["CaraPenyelesaian"] | null;
      /** Nominal Dibayar */
      nominal_dibayar: number | null;
      /** Tanggal Penyelesaian */
      tanggal_penyelesaian: string | null;
      /** Admin Pengonfirmasi */
      admin_pengonfirmasi: string | null;
    };
    /** TagihanRingkas */
    TagihanRingkas: {
      /** Id */
      id: number;
      /** Nominal */
      nominal: number;
    };
    /** TambahEksemplar */
    TambahEksemplar: {
      /** Jumlah */
      jumlah: number;
      /** Rak Id */
      rak_id: number;
    };
    /** TransaksiKeluar */
    TransaksiKeluar: {
      /** Id */
      id: number;
      anggota: components["schemas"]["app__schemas__peminjaman__AnggotaRingkas"];
      /**
       * Tanggal Transaksi
       * Format: date
       */
      tanggal_transaksi: string;
      /** Item */
      item: components["schemas"]["ItemDipinjamKeluar"][];
    };
    /**
     * UbahAnggotaAdminMasuk
     * @description FR-AKN-11, K-03: `password_baru` opsional, tanpa password lama.
     */
    UbahAnggotaAdminMasuk: {
      /** Nama */
      nama: string;
      /** Alamat */
      alamat: string;
      /** Email */
      email: string;
      /** Telepon */
      telepon: string;
      /** Password Baru */
      password_baru?: string | null;
    };
    /**
     * UbahProfilMasuk
     * @description FR-AKN-07: hanya isian ini yang boleh diubah anggota.
     */
    UbahProfilMasuk: {
      /** Nama */
      nama: string;
      /** Alamat */
      alamat: string;
      /** Email */
      email: string;
      /** Telepon */
      telepon: string;
    };
    /** UbahRak */
    UbahRak: {
      /** Rak Id */
      rak_id: number;
    };
    /** ValidasiItemMasuk */
    ValidasiItemMasuk: {
      /** Anggota Id */
      anggota_id: number;
      /** Kode Eksemplar */
      kode_eksemplar: string;
      /**
       * Keranjang
       * @default []
       */
      keranjang: string[];
    };
    /**
     * AnggotaRingkas
     * @description Sengaja tanpa NIK dan kontak.
     */
    app__schemas__hilang_rusak__AnggotaRingkas: {
      /** Kode */
      kode: string;
      /** Nama */
      nama: string;
    };
    /** AnggotaRingkas */
    app__schemas__peminjaman__AnggotaRingkas: {
      /** Kode */
      kode: string;
      /** Nama */
      nama: string;
    };
    /** KonfirmasiMasuk */
    app__schemas__peminjaman__KonfirmasiMasuk: {
      /** Anggota Id */
      anggota_id: number;
      /** Kode Eksemplar */
      kode_eksemplar: string[];
    };
    /** KonfirmasiMasuk */
    app__schemas__pengembalian__KonfirmasiMasuk: {
      /** Kode Eksemplar */
      kode_eksemplar: string;
    };
    /** GalatDetail */
    GalatDetail: {
      /** Kode */
      kode: string;
      /** Pesan */
      pesan: string;
      /**
       * Rujukan
       * @default null
       */
      rujukan: string | null;
      /**
       * Isian
       * @default null
       */
      isian: {
        [key: string]: string;
      } | null;
    };
    /** GalatRespons */
    GalatRespons: {
      detail: components["schemas"]["GalatDetail"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusHealth"];
        };
      };
    };
  };
  daftar_api_v1_auth_daftar_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_daftar_api_v1_auth_daftar_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HasilDaftarKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PermintaanLogin"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponsLogin"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  saya_api_v1_auth_saya_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponsSaya"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  cari_judul_api_v1_katalog_judul_get: {
    parameters: {
      query?: {
        /** @description Judul, penulis, ISBN, atau kategori */
        q?: string | null;
        halaman?: number;
        per_halaman?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HalamanKatalog"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  detail_judul_api_v1_katalog_judul__judul_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judul_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JudulKatalogKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  cover_judul_api_v1_katalog_judul__judul_id__cover_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judul_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "image/jpeg": unknown;
          "image/png": unknown;
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  daftar_kategori_api_v1_admin_kategori_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KategoriKeluar"][];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  tambah_kategori_api_v1_admin_kategori_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KategoriMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KategoriKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ubah_kategori_api_v1_admin_kategori__kategori_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kategori_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KategoriMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KategoriKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  hapus_kategori_api_v1_admin_kategori__kategori_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kategori_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  daftar_rak_api_v1_admin_rak_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RakKeluar"][];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  tambah_rak_api_v1_admin_rak_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RakMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RakKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ubah_rak_api_v1_admin_rak__rak_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rak_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RakMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RakKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  hapus_rak_api_v1_admin_rak__rak_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rak_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  daftar_judul_api_v1_admin_judul_get: {
    parameters: {
      query?: {
        halaman?: number;
        per_halaman?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HalamanJudul"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  tambah_judul_api_v1_admin_judul_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JudulMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JudulKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  detail_judul_api_v1_admin_judul__judul_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judul_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JudulKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ubah_judul_api_v1_admin_judul__judul_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judul_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JudulMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JudulKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  hapus_judul_api_v1_admin_judul__judul_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judul_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ganti_cover_api_v1_admin_judul__judul_id__cover_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judul_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_ganti_cover_api_v1_admin_judul__judul_id__cover_put"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JudulKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  stok_judul_api_v1_admin_judul__judul_id__eksemplar_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judul_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StokJudul"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  tambah_eksemplar_api_v1_admin_judul__judul_id__eksemplar_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judul_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TambahEksemplar"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EksemplarKeluar"][];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  data_label_api_v1_admin_eksemplar_label_get: {
    parameters: {
      query?: {
        id?: number[];
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelEksemplar"][];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ubah_rak_api_v1_admin_eksemplar__eksemplar_id__rak_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eksemplar_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UbahRak"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EksemplarKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  tandai_rusak_api_v1_admin_eksemplar__eksemplar_id__rusak_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eksemplar_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EksemplarKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  identifikasi_anggota_api_v1_admin_peminjaman_anggota__kode__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kode: string;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentitasAnggotaKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  validasi_item_api_v1_admin_peminjaman_validasi_item_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidasiItemMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemValidKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  konfirmasi_api_v1_admin_peminjaman_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["app__schemas__peminjaman__KonfirmasiMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransaksiKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  pratinjau_api_v1_admin_pengembalian__kode_eksemplar__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kode_eksemplar: string;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PratinjauKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  konfirmasi_api_v1_admin_pengembalian_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["app__schemas__pengembalian__KonfirmasiMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PengembalianKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  daftar_item_anggota_api_v1_admin_hilang_rusak_anggota__kode__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kode: string;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DaftarItemKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  catat_api_v1_admin_hilang_rusak_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CatatMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PencatatanKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  daftar_api_v1_admin_tagihan_get: {
    parameters: {
      query?: {
        status?: ("BELUM_LUNAS" | "LUNAS") | null;
        jenis?: ("DENDA" | "PENGGANTIAN") | null;
        /** @description Kode anggota (OQ-29) */
        anggota?: string | null;
        halaman?: number;
        per_halaman?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HalamanTagihan"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  detail_api_v1_admin_tagihan__tagihan_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tagihan_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TagihanKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  selesaikan_api_v1_admin_tagihan__tagihan_id__penyelesaian_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tagihan_id: number;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PenyelesaianMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TagihanKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  cari_api_v1_admin_anggota_get: {
    parameters: {
      query?: {
        /** @description ID (kode), NIK, atau nama (OQ-33) */
        q?: string | null;
        halaman?: number;
        per_halaman?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HalamanAnggota"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  detail_api_v1_admin_anggota__kode__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kode: string;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfilKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ubah_api_v1_admin_anggota__kode__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kode: string;
      };
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UbahAnggotaAdminMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfilKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  dashboard_api_v1_admin_dashboard_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DashboardKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  laporan_transaksi_api_v1_admin_laporan_transaksi_get: {
    parameters: {
      query?: {
        halaman?: number;
        per_halaman?: number;
        dari?: string | null;
        sampai?: string | null;
        /** @description ASUMSI(OQ-37): status item; TERLAMBAT turunan */
        status?: ("DIPINJAM" | "TERLAMBAT" | "DIKEMBALIKAN" | "HILANG" | "RUSAK") | null;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LaporanTransaksiKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ekspor_transaksi_api_v1_admin_laporan_transaksi_ekspor_get: {
    parameters: {
      query: {
        format: "pdf" | "xlsx";
        dari?: string | null;
        sampai?: string | null;
        /** @description ASUMSI(OQ-37): status item; TERLAMBAT turunan */
        status?: ("DIPINJAM" | "TERLAMBAT" | "DIKEMBALIKAN" | "HILANG" | "RUSAK") | null;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/pdf": unknown;
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  laporan_tagihan_api_v1_admin_laporan_tagihan_get: {
    parameters: {
      query?: {
        halaman?: number;
        per_halaman?: number;
        dari?: string | null;
        sampai?: string | null;
        jenis?: ("DENDA" | "PENGGANTIAN") | null;
        status?: ("BELUM_LUNAS" | "LUNAS") | null;
        cara?: ("TUNAI" | "TRANSFER" | "BUKU_PENGGANTI") | null;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LaporanTagihanKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ekspor_tagihan_api_v1_admin_laporan_tagihan_ekspor_get: {
    parameters: {
      query: {
        format: "pdf" | "xlsx";
        dari?: string | null;
        sampai?: string | null;
        jenis?: ("DENDA" | "PENGGANTIAN") | null;
        status?: ("BELUM_LUNAS" | "LUNAS") | null;
        cara?: ("TUNAI" | "TRANSFER" | "BUKU_PENGGANTI") | null;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/pdf": unknown;
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  profil_api_v1_anggota_profil_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfilKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ubah_profil_api_v1_anggota_profil_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UbahProfilMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfilKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  ganti_password_api_v1_anggota_profil_password_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GantiPasswordMasuk"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  qr_api_v1_anggota_qr_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QrKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  kelayakan_api_v1_anggota_kelayakan_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KelayakanKeluar"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  pinjaman_api_v1_anggota_pinjaman_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PinjamanAktifKeluar"][];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  riwayat_api_v1_anggota_riwayat_get: {
    parameters: {
      query?: {
        halaman?: number;
        per_halaman?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HalamanRiwayat"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
  tagihan_api_v1_anggota_tagihan_get: {
    parameters: {
      query?: {
        halaman?: number;
        per_halaman?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        sesi_perpus?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HalamanTagihanAnggota"];
        };
      };
      /** @description Validasi isian gagal */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GalatRespons"];
        };
      };
    };
  };
}
